# 网站主题配置
theme: jekyll-theme-chirpy  # 使用 Chirpy 主题

# 网站语言设置 › http://www.lingoes.net/en/translator/langcode.htm
# 如果与 `_data/locales` 文件夹中的文件名相同，则布局语言也会更改
# 否则，布局语言将使用默认的 'en' (英语)。
lang: en  # 网站语言，选择英文

# 设置时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai  # 可以设置你的时区，例如 "Asia/Shanghai"

# jekyll-seo-tag 插件设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: D.FS  # 站点主标题

tagline: 田里的麦子熟了,我的梦也该醒了  # 站点副标题，将显示在页面下方

description: >-  # 用于 SEO 元标签和 atom feed


# 填写站点的协议和主机名
# 例如，'https://username.github.io'，注意不要以 '/' 结尾
url: ""  # 如果部署到 GitHub Pages，可以留空，GitHub 会自动处理

# GitHub 设置
github:
  username: DmcforSpc  # 你的 GitHub 用户名

# Twitter 设置
# twitter:
#   username: twitter_username  # 你的 Twitter 用户名

# 社交媒体链接
social:
  name: dmcfor_spc  # 显示为默认的作者名称
  email: dmcfor_spc@outlook.com  # 你的邮箱地址
  links:
    # - https://twitter.com/username  # 你的 Twitter 主页链接
    - https://github.com/username  # 你的 GitHub 主页链接
    # 可以取消注释以下内容来添加更多社交媒体链接
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 站点验证设置
webmaster_verifications:
  google: # 填写你的 Google 验证码
  bing: # 填写你的 Bing 验证码
  alexa: # 填写你的 Alexa 验证码
  yandex: # 填写你的 Yandex 验证码
  baidu: # 填写你的 Baidu 验证码
  facebook: # 填写你的 Facebook 验证码

# ↑ --------------------------
# `jekyll-seo-tag` 插件的结束设置

# 网站分析设置
analytics:
  google:
    id: # 填写你的 Google Analytics ID
  goatcounter:
    id: # 填写你的 GoatCounter ID
  umami:
    id: # 填写你的 Umami ID
    domain: # 填写你的 Umami 域名
  matomo:
    id: # 填写你的 Matomo ID
    domain: # 填写你的 Matomo 域名
  cloudflare:
    id: # 填写你的 Cloudflare Web Analytics token
  fathom:
    id: # 填写你的 Fathom Site ID

# 页面视图设置
pageviews:
  provider: # 当前仅支持 'goatcounter'

# 偏好颜色模式设置
#
# 注：如果留空，将默认跟随系统的颜色偏好，
# 并且用户可以在左侧边栏的底部切换主题（深色或浅色模式）。
#
# 可选值：
#     light — 使用浅色主题
#     dark — 使用深色主题
theme_mode: dark # [light | dark]

# 媒体资源的 CDN 地址
# 一旦配置了 CDN，所有媒体资源（如站点头像、文章图片、音频和视频文件）的路径都会加上 CDN URL
#
# 例如，'https://cdn.com'
cdn:

# 侧边栏的头像，支持本地文件或跨域资源（CORS）
avatar: /touxiang/m.png

# 用于社交分享的预览图像，SEO `og:image` 元标签会使用这个图像
# 可以在页面的 Front Matter 中通过 `page.image` 来覆盖此设置
social_preview_image: # 本地文件或跨域资源（CORS）

# 开启/关闭文章的目录 (TOC) 功能
toc: true  # 默认开启 TOC 功能

comments:
  # 全局开关，启用或禁用评论系统
  provider: # [disqus | utterances | giscus]
  # 提供商选项如下：
  disqus:
    shortname: # 填写你的 Disqus 短名称 › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances 设置 › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # <url | pathname | title | ...>
  # Giscus 设置 › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # 可选，默认为 'pathname'
    strict: # 可选，默认为 '0'
    input_position: # 可选，默认为 'bottom'
    lang: # 可选，默认为 `site.lang` 的值
    reactions_enabled: # 可选，默认为 '1'

# 自托管静态资源（可选） › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # 布尔值，留空则为 false
    # 指定 Jekyll 环境，空则表示适用于所有环境
    env: # [development | production]

# PWA 设置
pwa:
  enabled: true # 启用 PWA 功能（可安装）
  cache:
    enabled: true # 启用 PWA 离线缓存
    # 以下路径将从 PWA 缓存中排除
    deny_paths:
      # - "/example"  # URLs 为 <SITE_URL>/example/* 的路径将不会被缓存

# 分页设置
paginate: 10  # 每页显示的文章数量

# 网站的基本 URL
baseurl: ""  # 如果部署到 GitHub Pages，可以留空

# ------------ 以下选项不推荐修改 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge  # 使用 Rouge 作为语法高亮工具
  syntax_highlighter_opts: # Rouge 配置 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # 这里的空字符串表示适用于所有文件
      type: posts
    values:
      layout: post
      comments: true # 在文章中启用评论
      toc: true # 在文章中显示 TOC
      permalink: /posts/:title/  # 文章的 permalink 格式
  - scope:
      path: _drafts
    values:
      comments: false  # 草稿文章不启用评论
  - scope:
      path: ""
      type: tabs  # 适用于 `tabs` 集合
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed  # 使用压缩的 CSS 样式

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]  # 开发环境忽略 HTML 压缩

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json  # 排除这些文件和目录

jekyll-archives:
  enabled: [categories, tags]  # 启用分类和标签归档
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/  # 设置分类和标签的 URL 路径
